version: '3'

services:
  tracker:
    image: "morunchang/fastdfs"
    ports:
      - "22122:22122"
    entrypoint: sh tracker.sh
  storage:
    depends_on:
      - tracker
    build: ./storage
    environment:
      GROUP_NAME: group1
      TRACKER_IP: 49.233.70.50:22122
    ports:
      - "80:80"
      - "23000:23000"
    volumes:
      - /leyou/tracker:/data/fast_data
